### ISSUE TITLE
[feat] - validate and merge okto wallet 

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/wallet-aggregator-sdk#33]
PR - https://github.com/XLabs/wallet-aggregator-sdk/pull/30

```[tasklist]
### Tasks
- [ ] Review the PR
- [ ] Merge and test it locally and/or at portal bridge preview
- [ ] release a new package version
- [ ] bump version at connect
- [ ] bump version at legacy (aka advanced tools)
```
